env:
  global:
    - CC_TEST_REPORTER_ID=be843db42f818fed42aca6e6101b1630e6e7a4c597467f1938820db732f206a4
language: python
email:
  on_success: always
  on_failure: always
python:
  - "3.6"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - pytest --cov-report xml --cov=sdds test
  - travis-sphinx build --source=doc/ --nowarn
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - travis-sphinx deploy

